"""add_cash_register_simple_tables

Revision ID: 5a569e9cc1e6
Revises: 72bf052c5ed3
Create Date: 2026-06-19 02:33:02.908639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a569e9cc1e6'
down_revision: Union[str, Sequence[str], None] = '72bf052c5ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_register_day_closures',
    sa.Column('closed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=False),
    sa.Column('total_sales_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_sales_count', sa.Integer(), nullable=False),
    sa.Column('cash_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mobile_money_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('card_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expected_cash_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('real_cash_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('difference_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['tenant_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cash_register_day_closures_created_at', 'cash_register_day_closures', ['created_at'], unique=False)
    op.create_index('ix_cash_register_day_closures_tenant_id', 'cash_register_day_closures', ['tenant_id'], unique=False)
    op.create_table('cash_register_sales',
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_received', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('change_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_user_id', sa.UUID(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['tenant_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['tenant_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cash_register_sales_created_at', 'cash_register_sales', ['created_at'], unique=False)
    op.create_index('ix_cash_register_sales_status', 'cash_register_sales', ['status'], unique=False)
    op.create_index(op.f('ix_cash_register_sales_tenant_id'), 'cash_register_sales', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_register_sales_tenant_id'), table_name='cash_register_sales')
    op.drop_index('ix_cash_register_sales_status', table_name='cash_register_sales')
    op.drop_index('ix_cash_register_sales_created_at', table_name='cash_register_sales')
    op.drop_table('cash_register_sales')
    op.drop_index('ix_cash_register_day_closures_tenant_id', table_name='cash_register_day_closures')
    op.drop_index('ix_cash_register_day_closures_created_at', table_name='cash_register_day_closures')
    op.drop_table('cash_register_day_closures')
    # ### end Alembic commands ###
