"""add_tenant_foreign_keys

Revision ID: a3fbd72007c0
Revises: f699a0844667
Create Date: 2026-06-18 23:25:49.101418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3fbd72007c0'
down_revision: Union[str, Sequence[str], None] = 'f699a0844667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'billing_invoice_items', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'billing_invoices', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'billing_payment_methods', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'billing_payments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subscription_events', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subscription_scheduled_changes', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subscriptions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tenant_audit_logs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tenant_invitations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tenant_modules', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tenant_refresh_tokens', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tenant_roles', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tenant_settings', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tenant_users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'usage_counters', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'usage_events', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage_events', type_='foreignkey')
    op.drop_constraint(None, 'usage_counters', type_='foreignkey')
    op.drop_constraint(None, 'tenant_users', type_='foreignkey')
    op.drop_constraint(None, 'tenant_settings', type_='foreignkey')
    op.drop_constraint(None, 'tenant_roles', type_='foreignkey')
    op.drop_constraint(None, 'tenant_refresh_tokens', type_='foreignkey')
    op.drop_constraint(None, 'tenant_modules', type_='foreignkey')
    op.drop_constraint(None, 'tenant_invitations', type_='foreignkey')
    op.drop_constraint(None, 'tenant_audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscription_scheduled_changes', type_='foreignkey')
    op.drop_constraint(None, 'subscription_events', type_='foreignkey')
    op.drop_constraint(None, 'billing_payments', type_='foreignkey')
    op.drop_constraint(None, 'billing_payment_methods', type_='foreignkey')
    op.drop_constraint(None, 'billing_invoices', type_='foreignkey')
    op.drop_constraint(None, 'billing_invoice_items', type_='foreignkey')
    # ### end Alembic commands ###
